apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: service1-config
      containers:
        - name: app
          volumeMounts:
          - name: config-volume
            mountPath: /config
