apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - http:
      paths:
      - path: /changeme
        backend:
          serviceName: svc
          servicePort: 8080
