namespace: default
resources:
- github.com/miklosn/kust-example/base/dpl-autoscale-ingress
namePrefix: service1-
commonLabels:
  service_name: service1
  service_type: go
  service_group: group1
  team: team2
patchesStrategicMerge:
- patch_env.yaml
patches:
- target:
    kind: Ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/http/paths/0/path
      value: /service1
